---
title: "Untitled"
format: html
---


```{r}
install.packages("dplyr")
install.packages("BiocManager")
install.packages("purrr")
install.packages("stringr")
install.packages("ggplot2")
install.packages("ggcyto")
install.packages("tidyr")
install.packages("xml2")
install.packages("lubridate")
install.packages("httr2")
install.packages("devtools")
install.packages("plotly")
install.packages("Rtsne")
install.packages("uwot")

# Following packages require BiocManager to be loaded
BiocManager::install("ComplexHeatmap")
install("PeacoQC")
install("remotes")
BiocManager::install("flowCore")
BiocManager::install("flowWorkspace")
BiocManager::install("openCyto")
BiocManager::install("FlowSOM")
BiocManager::install("flowGate")
BiocManager::install("CytoML")

# Remember to load devtools to use install_github function
install_github("hally166/flowSpectrum")
install_github("saeyslab/CytoNorm")
install_github("biosurf/cyCombine")

# Remember to load remotes to install the following packages
remotes::install_version("ggplot2", version = "3.5.2", repos = "https://cloud.r-project.org")
```

```{r}
library(dplyr)
library(BiocManager)
library(PeacoQC)
library(remotes)
library(devtools)
library(purrr)
```
```{r}
sessionInfo()
```
